export enum EndpointType {
    SPOTIFY_AUTH = "SPOTIFY_AUTH",
    SPOTIFY_AUTH_TOKEN = "SPOTIFY_AUTH_TOKEN",
    SPOTIFY_CALLBACK = "SPOTIFY_CALLBACK",
    SPOTIFY_GET_CURRENT_USER_PROFILE = "SPOTIFY_GET_CURRENT_USER_PROFILE",
}